version: "3.8"

services:
  frontend:
    container_name: composesync-frontend
    build: ./client
    ports:
      - 3000:3000
    networks:
      - composesync-network
    command: npm start

  backend:
    container_name: composesync-backend
    build: .
    ports:
      - 5000:5000
    networks:
      - composesync-network
    command: nodemon server

networks:
  composesync-network: